### ISSUE TITLE
exploreHeights.R added, illustrating use of functions and unitTests

### ISSUE THREAD

**Issue by paul-shannon** [danibergey/intro-R#1]
Hi Dani,

You can run this by
- starting R
- source("exploreHeights.R")
- runTests()

This illustrates a code writing style called "test-driven development".  It may seem like lots of added this-will-slow-me-down code, but in fact it soon leads to developing code faster, and better.

A challenge question:  there is a browser() command in the file now, currently commented out.  What might I have used that for?  Hint:  it is incredibly useful in debugging...

**Comment by danibergey** [comment]
Do you recommend downloading GitHub to my desktop? I am doing that now. Or, I guess, I'm curious what the easiest way to use this file would be other than copy and paste? Maybe there's something that I'm missing on the site.
